In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv("Student Mental health.csv")
df.head()

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
0,8/7/2020 12:02,Female,18.0,Engineering,year 1,3.00 - 3.49,No,Yes,No,Yes,No
1,8/7/2020 12:04,Male,21.0,Islamic education,year 2,3.00 - 3.49,No,No,Yes,No,No
2,8/7/2020 12:05,Male,19.0,BIT,Year 1,3.00 - 3.49,No,Yes,Yes,Yes,No
3,8/7/2020 12:06,Female,22.0,Laws,year 3,3.00 - 3.49,Yes,Yes,No,No,No
4,8/7/2020 12:13,Male,23.0,Mathemathics,year 4,3.00 - 3.49,No,No,No,No,No

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 11 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Timestamp                                     101 non-null    object
 1   Choose your gender                            101 non-null    object
 2   Age                                           101 non-null    float64
 3   What is your course?                          101 non-null    object
 4   Your current year of Study                    101 non-null    object
 5   What is your CGPA?                            101 non-null    object
 6   Marital status                                101 non-null    object
 7   Do you have Depression?                       101 non-null    object
 8   Do you have Anxiety?                          101 non-null    object
 9   Do you have Panic attack?                     101 non-null    object
 10  Did you seek any specialist for a treatment?  101 non-null    object
dtypes: float64(1), object(10)
memory usage: 8.8+ KB

In [ ]:
median = df['Age'].median()
df['Age'].fillna(median, inplace = True)

/tmp/ipython-input-456254063.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(median, inplace = True)

In [ ]:
df_copy = df.copy()
for col in ['Do you have Anxiety?', 'Do you have Panic attack?', 'Do you have Depression?']:
    df_copy[col] = df_copy[col].map({'Yes': 1, 'No': 0})
df_copy['mental_issue'] = df_copy[['Do you have Anxiety?', 'Do you have Panic attack?', 'Do you have Depression?']].sum(axis = 1)
def classify(count):
  if count == 0:
    return 1
  elif count > 0 and count <= 2:
    return 2
  else:
    return 3

df_copy['mental_issue'] = df_copy['mental_issue'].apply(classify)
df_copy.head()

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?,mental_issue
0,8/7/2020 12:02,Female,18.0,Engineering,year 1,3.00 - 3.49,No,1,0,1,No,2
1,8/7/2020 12:04,Male,21.0,Islamic education,year 2,3.00 - 3.49,No,0,1,0,No,2
2,8/7/2020 12:05,Male,19.0,BIT,Year 1,3.00 - 3.49,No,1,1,1,No,3
3,8/7/2020 12:06,Female,22.0,Laws,year 3,3.00 - 3.49,Yes,1,0,0,No,2
4,8/7/2020 12:13,Male,23.0,Mathemathics,year 4,3.00 - 3.49,No,0,0,0,No,1

In [ ]:
df = df_copy
df

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?,mental_issue
0,8/7/2020 12:02,Female,18.0,Engineering,year 1,3.00 - 3.49,No,1,0,1,No,2
1,8/7/2020 12:04,Male,21.0,Islamic education,year 2,3.00 - 3.49,No,0,1,0,No,2
2,8/7/2020 12:05,Male,19.0,BIT,Year 1,3.00 - 3.49,No,1,1,1,No,3
3,8/7/2020 12:06,Female,22.0,Laws,year 3,3.00 - 3.49,Yes,1,0,0,No,2
4,8/7/2020 12:13,Male,23.0,Mathemathics,year 4,3.00 - 3.49,No,0,0,0,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...
96,13/07/2020 19:56:49,Female,21.0,BCS,year 1,3.50 - 4.00,No,0,1,0,No,2
97,13/07/2020 21:21:42,Male,18.0,Engineering,Year 2,3.00 - 3.49,No,1,1,0,No,2
98,13/07/2020 21:22:56,Female,19.0,Nursing,Year 3,3.50 - 4.00,Yes,1,0,1,No,2
99,13/07/2020 21:23:57,Female,23.0,Pendidikan Islam,year 4,3.50 - 4.00,No,0,0,0,No,1
100,18/07/2020 20:16:21,Male,20.0,Biomedical science,Year 2,3.00 - 3.49,No,0,0,0,No,1

In [ ]:
list(df)

['Timestamp',
 'Choose your gender',
 'Age',
 'What is your course?',
 'Your current year of Study',
 'What is your CGPA?',
 'Marital status',
 'Do you have Depression?',
 'Do you have Anxiety?',
 'Do you have Panic attack?',
 'Did you seek any specialist for a treatment?',
 'mental_issue']

In [ ]:
df.rename(columns={
    'Choose your gender': 'gender',
    'Age': 'age',
    'What is your course?': 'course',
    'Your current year of Study': 'study_year',
    'What is your CGPA?': 'cgpa',
    'Marital status': 'marital_status',
    'Do you have Depression?': 'depression',
    'Do you have Anxiety?': 'anxiety',
    'Do you have Panic attack?': 'panic_attack',
    'Did you seek any specialist for a treatment?': 'sought_treatment',
    'mental_issue': 'mental_issue'  # already fine
}, inplace=True)

In [ ]:
df.head()

,Timestamp,gender,age,course,study_year,cgpa,marital_status,depression,anxiety,panic_attack,sought_treatment,mental_issue
0,8/7/2020 12:02,Female,18.0,Engineering,year 1,3.00 - 3.49,No,1,0,1,No,2
1,8/7/2020 12:04,Male,21.0,Islamic education,year 2,3.00 - 3.49,No,0,1,0,No,2
2,8/7/2020 12:05,Male,19.0,BIT,Year 1,3.00 - 3.49,No,1,1,1,No,3
3,8/7/2020 12:06,Female,22.0,Laws,year 3,3.00 - 3.49,Yes,1,0,0,No,2
4,8/7/2020 12:13,Male,23.0,Mathemathics,year 4,3.00 - 3.49,No,0,0,0,No,1

In [ ]:
copy = pd.get_dummies(df, columns=['course'], prefix='course').copy()
copy

,Timestamp,gender,age,study_year,cgpa,marital_status,depression,anxiety,panic_attack,sought_treatment,...,course_Pendidikan Islam,course_Pendidikan Islam,course_Pendidikan islam,course_Psychology,course_Radiography,course_TAASL,course_Usuluddin,course_engin,course_koe,course_psychology
0,8/7/2020 12:02,Female,18.0,year 1,3.00 - 3.49,No,1,0,1,No,...,False,False,False,False,False,False,False,False,False,False
1,8/7/2020 12:04,Male,21.0,year 2,3.00 - 3.49,No,0,1,0,No,...,False,False,False,False,False,False,False,False,False,False
2,8/7/2020 12:05,Male,19.0,Year 1,3.00 - 3.49,No,1,1,1,No,...,False,False,False,False,False,False,False,False,False,False
3,8/7/2020 12:06,Female,22.0,year 3,3.00 - 3.49,Yes,1,0,0,No,...,False,False,False,False,False,False,False,False,False,False
4,8/7/2020 12:13,Male,23.0,year 4,3.00 - 3.49,No,0,0,0,No,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,13/07/2020 19:56:49,Female,21.0,year 1,3.50 - 4.00,No,0,1,0,No,...,False,False,False,False,False,False,False,False,False,False
97,13/07/2020 21:21:42,Male,18.0,Year 2,3.00 - 3.49,No,1,1,0,No,...,False,False,False,False,False,False,False,False,False,False
98,13/07/2020 21:22:56,Female,19.0,Year 3,3.50 - 4.00,Yes,1,0,1,No,...,False,False,False,False,False,False,False,False,False,False
99,13/07/2020 21:23:57,Female,23.0,year 4,3.50 - 4.00,No,0,0,0,No,...,True,False,False,False,False,False,False,False,False,False
100,18/07/2020 20:16:21,Male,20.0,Year 2,3.00 - 3.49,No,0,0,0,No,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
copy['gender'] = le.fit_transform(copy['gender'])
copy['marital_status'] = le.fit_transform(copy['marital_status'])
copy['sought_treatment'] = le.fit_transform(copy['sought_treatment'])
copy.head(2)

,Timestamp,gender,age,study_year,cgpa,marital_status,depression,anxiety,panic_attack,sought_treatment,...,course_Pendidikan Islam,course_Pendidikan Islam,course_Pendidikan islam,course_Psychology,course_Radiography,course_TAASL,course_Usuluddin,course_engin,course_koe,course_psychology
0,8/7/2020 12:02,0,18.0,year 1,3.00 - 3.49,0,1,0,1,0,...,False,False,False,False,False,False,False,False,False,False
1,8/7/2020 12:04,1,21.0,year 2,3.00 - 3.49,0,0,1,0,0,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
copy['study_year'] = copy['study_year'].str.lower()
copy['study_year'] = copy['study_year'].str.extract('(\d)').astype(int)

In [ ]:
copy.head(2)

,Timestamp,gender,age,study_year,cgpa,marital_status,depression,anxiety,panic_attack,sought_treatment,...,course_Pendidikan Islam,course_Pendidikan Islam,course_Pendidikan islam,course_Psychology,course_Radiography,course_TAASL,course_Usuluddin,course_engin,course_koe,course_psychology
0,8/7/2020 12:02,0,18.0,1,3.00 - 3.49,0,1,0,1,0,...,False,False,False,False,False,False,False,False,False,False
1,8/7/2020 12:04,1,21.0,2,3.00 - 3.49,0,0,1,0,0,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
df['cgpa'].value_counts()

cgpa
3.50 - 4.00     47
3.00 - 3.49     43
2.50 - 2.99      4
0 - 1.99         4
2.00 - 2.49      2
3.50 - 4.00      1
Name: count, dtype: int64

In [ ]:
cgpa_map = {
    '0 - 1.99': 1,
    '2.00 - 2.49': 1,
    '2.50 - 2.99': 2,
    '3.00 - 3.49': 2,
    '3.50 - 4.00': 3
}

copy['cgpa'] = copy['cgpa'].map(cgpa_map)

In [ ]:
copy.head(2)

,Timestamp,gender,age,study_year,cgpa,marital_status,depression,anxiety,panic_attack,sought_treatment,...,course_Pendidikan Islam,course_Pendidikan islam,course_Psychology,course_Radiography,course_TAASL,course_Usuluddin,course_engin,course_koe,course_psychology,cgpa_level
0,8/7/2020 12:02,0,18.0,1,2.0,0,1,0,1,0,...,False,False,False,False,False,False,False,False,False,2.0
1,8/7/2020 12:04,1,21.0,2,2.0,0,0,1,0,0,...,False,False,False,False,False,False,False,False,False,2.0

In [ ]:
copy.fillna(0, inplace = True)
missing = copy.isnull().sum()
missing = missing[missing > 0].sort_values(ascending = False)
missing

Series([], dtype: int64)

In [ ]:
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
x = copy.drop(columns = ['Timestamp', 'mental_issue'])
y = copy['mental_issue']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, stratify = y, random_state = 42)
print(y.value_counts())

mental_issue
2    54
1    37
3    10
Name: count, dtype: int64

In [ ]:
log_model = LogisticRegression(max_iter = 1000, solver = 'lbfgs', class_weight = 'balanced')
log_model.fit(x_train, y_train)
log_pred = log_model.predict(x_test)
log_accuracy = accuracy_score(y_test, log_pred)
print(f"Logistic Regression Accuracy: {log_accuracy}")
print(classification_report(y_test, log_pred))

Logistic Regression Accuracy: 0.8387096774193549
              precision    recall  f1-score   support

           1       0.77      0.91      0.83        11
           2       0.93      0.76      0.84        17
           3       0.75      1.00      0.86         3

    accuracy                           0.84        31
   macro avg       0.82      0.89      0.84        31
weighted avg       0.85      0.84      0.84        31

In [ ]:
from sklearn.model_selection import cross_val_score
cross_val_score(log_model, x, y, cv=5, scoring='f1_weighted')

array([1.       , 1.       , 1.       , 1.       , 0.9501548])

In [ ]:
print(np.array_equal(x_train, x_test))
print(copy.duplicated().sum())
print(x_train.shape, x_test.shape)

False
0
(70, 59) (31, 59)

In [ ]:
forest = RandomForestClassifier(n_estimators = 100, random_state = 42, class_weight = 'balanced')
forest.fit(x_train, y_train)
forest_pred = forest.predict(x_test)
forest_accuracy = accuracy_score(y_test, forest_pred)
print(f"Random Forest Accuracy: {forest_accuracy}")
print(classification_report(y_test, forest_pred))

Random Forest Accuracy: 0.967741935483871
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        11
           2       0.94      1.00      0.97        17
           3       1.00      0.67      0.80         3

    accuracy                           0.97        31
   macro avg       0.98      0.89      0.92        31
weighted avg       0.97      0.97      0.96        31

In [ ]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC

model = OneVsRestClassifier(SVC(kernel='linear'))
model.fit(x_train, y_train)
svm_pred = model.predict(x_test)
svm_accuracy = accuracy_score(y_test, svm_pred)
print(f"SVM Accuracy: {svm_accuracy}")
print(classification_report(y_test, svm_pred))

SVM Accuracy: 0.8709677419354839
              precision    recall  f1-score   support

           1       0.92      1.00      0.96        11
           2       0.84      0.94      0.89        17
           3       0.00      0.00      0.00         3

    accuracy                           0.87        31
   macro avg       0.59      0.65      0.62        31
weighted avg       0.79      0.87      0.83        31

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
import sklearn
print(sklearn.__version__)

1.6.1

In [ ]:
import joblib

# Save the Random Forest model
joblib.dump(forest, 'random_forest_model.pkl')

['random_forest_model.pkl']

In [ ]:
pip show scikit-learn

Name: scikit-learn
Version: 1.6.1
Summary: A set of python modules for machine learning and data mining
Home-page: https://scikit-learn.org
Author:
Author-email:
License: BSD 3-Clause License

 Copyright (c) 2007-2024 The scikit-learn developers.
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

 * Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

 ----

 This binary distribution of scikit-learn also bundles the following software:

 ----

 Name: GCC runtime library
 Files: scikit_learn.libs/libgomp*.so*
 Availability: https://gcc.gnu.org/git/?p=gcc.git;a=tree;f=libgomp

 GCC RUNTIME LIBRARY EXCEPTION

 Version 3.1, 31 March 2009

 Copyright (C) 2009 Free Software Foundation, Inc. <http://fsf.org/>

 Everyone is permitted to copy and distribute verbatim copies of this
 license document, but changing it is not allowed.

 This GCC Runtime Library Exception ("Exception") is an additional
 permission under section 7 of the GNU General Public License, version
 3 ("GPLv3"). It applies to a given file (the "Runtime Library") that
 bears a notice placed by the copyright holder of the file stating that
 the file is governed by GPLv3 along with this Exception.

 When you use GCC to compile a program, GCC may combine portions of
 certain GCC header files and runtime libraries with the compiled
 program. The purpose of this Exception is to allow compilation of
 non-GPL (including proprietary) programs to use, in this way, the
 header files and runtime libraries covered by this Exception.

 0. Definitions.

 A file is an "Independent Module" if it either requires the Runtime
 Library for execution after a Compilation Process, or makes use of an
 interface provided by the Runtime Library, but is not otherwise based
 on the Runtime Library.

 "GCC" means a version of the GNU Compiler Collection, with or without
 modifications, governed by version 3 (or a specified later version) of
 the GNU General Public License (GPL) with the option of using any
 subsequent versions published by the FSF.

 "GPL-compatible Software" is software whose conditions of propagation,
 modification and use would permit combination with GCC in accord with
 the license of GCC.

 "Target Code" refers to output from any compiler for a real or virtual
 target processor architecture, in executable form or suitable for
 input to an assembler, loader, linker and/or execution
 phase. Notwithstanding that, Target Code does not include data in any
 format that is used as a compiler intermediate representation, or used
 for producing a compiler intermediate representation.

 The "Compilation Process" transforms code entirely represented in
 non-intermediate languages designed for human-written code, and/or in
 Java Virtual Machine byte code, into Target Code. Thus, for example,
 use of source code generators and preprocessors need not be considered
 part of the Compilation Process, since the Compilation Process can be
 understood as starting with the output of the generators or
 preprocessors.

 A Compilation Process is "Eligible" if it is done using GCC, alone or
 with other GPL-compatible software, or if it is done without using any
 work based on GCC. For example, using non-GPL-compatible Software to
 optimize any GCC intermediate representations would not qualify as an
 Eligible Compilation Process.

 1. Grant of Additional Permission.

 You have permission to propagate a work of Target Code formed by
 combining the Runtime Library with Independent Modules, even if such
 propagation would otherwise violate the terms of GPLv3, provided that
 all Target Code was generated by Eligible Compilation Processes. You
 may then convey such a combination under terms of your choice,
 consistent with the licensing of the Independent Modules.

 2. No Weakening of GCC Copyleft.

 The availability of this Exception does not imply any general
 presumption that third-party software is unaffected by the copyleft
 requirements of the license of GCC.

Location: /usr/local/lib/python3.11/dist-packages
Requires: joblib, numpy, scipy, threadpoolctl
Required-by: cuml-cu12, fastai, hdbscan, imbalanced-learn, libpysal, librosa, mlxtend, pynndescent, sentence-transformers, shap, sklearn-compat, sklearn-pandas, tsfresh, umap-learn, yellowbrick

In [ ]:
%%writefile app.py
import streamlit as st
import pandas as pd
import joblib
from sklearn.preprocessing import LabelEncoder

Writing app.py

In [ ]:
%%writefile -a app.py

# Load the trained Random Forest model
model = joblib.load('random_forest_model.pkl')

st.title('Student Mental Health Prediction')

st.write("""
This app predicts the mental health issue level of a student based on various factors.
Mental Health Issue Levels:
1: No issues
2: Moderate issues (Anxiety OR Panic Attack OR Depression)
3: Severe issues (Two or more issues)
""")

Appending to app.py

In [ ]:
%%writefile -a app.py

# Define the input fields
st.header('Enter Student Details:')

gender = st.selectbox('Choose your gender', ['Female', 'Male'])
age = st.number_input('Age', min_value=0, max_value=100, value=20)
course = st.selectbox('What is your course?', ['Engineering', 'Islamic education', 'BIT', 'Laws', 'Mathemathics', 'BCS', 'Human Resources', 'Irkhs', 'Psychology', 'KENMS', 'Accounting ', 'Medical Sciences', 'Pendidikan Islam ', 'Pendidikan Islam', 'Radiography', 'Dakwah', 'Diploma Nursing', 'Usuluddin ', 'FCIM', 'TAASL', 'Engine', 'Laws ', 'Kop', 'IRKHS', 'Dentistry', 'IT', 'CTS', 'engin', 'Econs', 'removing', 'psychology', 'koe', 'Kirkhs', 'Usuluddin', 'FSTE', 'Biomedical science', 'koe', 'BENL', 'Banking Studies', 'Diploma Science', 'MHSC', 'Malaysian studies', 'Nursing ', 'Pendidikan Islam', 'Human Sciences', 'business', 'Addin', 'Marine science', 'Pharmacy', 'Stock market ', 'Biotechnology', 'Communication ', 'Warning', 'Business Administration', 'Fiqh fatwa ', 'DVM ', 'Management ', 'syariah law ', 'Radiology', 'Diploma', 'Qaaf', 'Science', 'KOE', 'Islamic Education', 'Human science ', 'Biomedical Science', 'engin', 'Islamic finance', '建築工程', 'KMK', 'business', 'Diagnostic imaging ', 'Business', 'Law', 'Islamic finance ', 'Business', 'Diploma in accountancy', 'Renewable energy', 'Psychology', 'ENGINEERING', 'Banking islam', 'Software Engineering', 'Usul Fiqh ', 'Islamic Studies', 'engin ', 'ENM', 'Diploma in English', 'amway', 'Biotechnology ', 'Communication', 'Pendidikan', 'koe ', 'Fiqh', 'Islamic ed', 'Islamic Studies ', 'Aqidah', 'Manufacture', 'BIT ', 'Kirkhs ', 'Benl', 'IT ', 'machinical engineering', 'Laws', 'psychology', 'Pendidikan Islam', 'Human Science', 'Bcshons ', 'Marine science', 'Human resource', 'Accounting', 'Psychology', 'Radiography', 'TAASL', 'Usuluddin', 'engin', 'koe', 'psychology']) # Add all unique courses from your data
study_year = st.selectbox('Your current year of Study', [1, 2, 3, 4]) # Assuming years are 1, 2, 3, 4
cgpa = st.selectbox('What is your CGPA?', ['0 - 1.99', '2.00 - 2.49', '2.50 - 2.99', '3.00 - 3.49', '3.50 - 4.00'])
marital_status = st.selectbox('Marital status', ['No', 'Yes'])
sought_treatment = st.selectbox('Did you seek any specialist for a treatment?', ['No', 'Yes'])

Appending to app.py

In [ ]:
%%writefile -a app.py

# Preprocess user input
def preprocess_input(gender, age, course, study_year, cgpa, marital_status, sought_treatment):
    data = {'gender': gender,
            'age': age,
            'course': course,
            'study_year': study_year,
            'cgpa': cgpa,
            'marital_status': marital_status,
            'sought_treatment': sought_treatment,
            # Add these columns with default value 0 as they were in x_train
            'depression': 0,
            'anxiety': 0,
            'panic_attack': 0
           }
    df_input = pd.DataFrame([data])

    # Apply the same preprocessing as in the notebook
    # Ordinal encoding for year of study
    df_input['study_year'] = df_input['study_year'].astype(int)

    # Mapping for CGPA
    cgpa_map = {
        '0 - 1.99': 1,
        '2.00 - 2.49': 1,
        '2.50 - 2.99': 2,
        '3.00 - 3.49': 2,
        '3.50 - 4.00': 3
    }
    df_input['cgpa'] = df_input['cgpa'].map(cgpa_map)

    # Label encoding for binary categorical features
    for col in ['gender', 'marital_status', 'sought_treatment']:
        le = LabelEncoder()
        # We need to fit the encoder on all possible values from the original dataset
        # To avoid errors with unseen values
        # Assuming you have access to the original df or a list of unique values
        if col == 'gender':
            le.fit(['Female', 'Male'])
        elif col == 'marital_status':
            le.fit(['No', 'Yes'])
        elif col == 'sought_treatment':
            le.fit(['No', 'Yes'])
        df_input[col] = le.transform(df_input[col])


    # One-hot encoding for 'course' - ensure all possible courses are included
    # This requires having the list of all unique courses from the original data
    all_courses = ['Engineering', 'Islamic education', 'BIT', 'Laws', 'Mathemathics', 'BCS', 'Human Resources', 'Irkhs', 'Psychology', 'KENMS', 'Accounting ', 'Medical Sciences', 'Pendidikan Islam ', 'Pendidikan Islam', 'Radiography', 'Dakwah', 'Diploma Nursing', 'Usuluddin ', 'FCIM', 'TAASL', 'Engine', 'Laws ', 'Kop', 'IRKHS', 'Dentistry', 'IT', 'CTS', 'engin', 'Econs', 'removing', 'psychology', 'koe', 'Kirkhs', 'Usuluddin', 'FSTE', 'Biomedical science', 'koe', 'BENL', 'Banking Studies', 'Diploma Science', 'MHSC', 'Malaysian studies', 'Nursing ', 'Pendidikan Islam', 'Human Sciences', 'business', 'Addin', 'Marine science', 'Pharmacy', 'Stock market ', 'Biotechnology', 'Communication ', 'Warning', 'Business Administration', 'Fiqh fatwa ', 'DVM ', 'Management ', 'syariah law ', 'Radiology', 'Diploma', 'Qaaf', 'Science', 'KOE', 'Islamic Education', 'Human science ', 'Biomedical Science', 'engin', 'Islamic finance', '建築工程', 'KMK', 'business', 'Diagnostic imaging ', 'Business', 'Law', 'Islamic finance ', 'Business', 'Diploma in accountancy', 'Renewable energy', 'Psychology', 'ENGINEERING', 'Banking islam', 'Software Engineering', 'Usul Fiqh ', 'Islamic Studies', 'engin ', 'ENM', 'Diploma in English', 'amway', 'Biotechnology ', 'Communication', 'Pendidikan', 'koe ', 'Fiqh', 'Islamic ed', 'Islamic Studies ', 'Aqidah', 'Manufacture', 'BIT ', 'Kirkhs ', 'Benl', 'IT ', 'machinical engineering', 'Laws', 'psychology', 'Pendidikan Islam', 'Human Science', 'Bcshons ', 'Marine science', 'Human resource', 'Accounting', 'Psychology', 'Radiography', 'TAASL', 'Usuluddin', 'engin', 'koe', 'psychology'] # Replace with your actual list of unique courses
    df_input = pd.get_dummies(df_input, columns=['course'], prefix='course')

    # Ensure all course columns from training data are present, fill missing with 0
    for course in all_courses:
        if f'course_{course}' not in df_input.columns:
            df_input[f'course_{course}'] = 0

    # Load the exact column names from the training data
    try:
        train_columns = joblib.load('x_train_columns.pkl')
    except FileNotFoundError:
        st.error("Error: x_train_columns.pkl not found. Make sure you have uploaded this file.")
        return None

    # Reindex the input DataFrame to match the training data columns and fill missing values with 0
    df_input = df_input.reindex(columns=train_columns, fill_value=0)

    return df_input

Appending to app.py

In [ ]:
%%writefile -a app.py

# Create a button to make predictions
if st.button('Predict Mental Health Issue Level'):
    # Preprocess the input
    processed_input = preprocess_input(gender, age, course, study_year, cgpa, marital_status, sought_treatment)

    # Make prediction
    prediction = model.predict(processed_input)

    # Display the prediction
    st.header('Prediction:')
    if prediction[0] == 1:
        st.success('Predicted Mental Health Issue Level: 1 (No issues)')
    elif prediction[0] == 2:
        st.warning('Predicted Mental Health Issue Level: 2 (Moderate issues)')
    else:
        st.error('Predicted Mental Health Issue Level: 3 (Severe issues)')

Appending to app.py

In [ ]:
import joblib

try:
    loaded_model = joblib.load('random_forest_model.pkl')
    print(f"Model loaded successfully. Type of loaded object: {type(loaded_model)}")
except Exception as e:
    print(f"Error loading the model: {e}")

Model loaded successfully. Type of loaded object: <class 'sklearn.ensemble._forest.RandomForestClassifier'>

In [ ]:
# Save the column names of x_train
import joblib
joblib.dump(x_train.columns.tolist(), "x_train_columns.pkl")

['x_train_columns.pkl']

# Task
Update the Python script "app.py" to use a scikit-learn Pipeline for preprocessing and prediction with a RandomForestClassifier model, addressing the `ValueError: The feature names should match those that were passed during fit` by ensuring consistent feature handling between training and inference.

## Identify preprocessing steps

### Subtask:
Identify preprocessing steps for each column based on the previous steps in the notebook.

**Reasoning**:
Analyze the previous code cells to identify the preprocessing steps applied to each column and categorize them accordingly.

In [ ]:
# Identify dropped columns
dropped_columns = ['Timestamp']

# Identify binary categorical columns label encoded
label_encoded_cols = ['gender', 'marital_status', 'sought_treatment']

# Identify ordinal categorical columns mapped to numerical
ordinal_mapped_cols = ['study_year', 'cgpa']

# Identify nominal categorical columns one-hot encoded
one_hot_encoded_cols = ['course']

# Identify numerical columns kept as is
numerical_cols = ['age']

# Columns created during preprocessing that are used as features (from the sum of binary depression/anxiety/panic)
# These columns are already present in x_train, so we don't need to process them from the original input in the app
# They will be added with default 0 in the app's preprocessing function.
# features_from_binary_sum = ['depression', 'anxiety', 'panic_attack']

print("Dropped Columns:", dropped_columns)
print("Label Encoded Columns:", label_encoded_cols)
print("Ordinal Mapped Columns:", ordinal_mapped_cols)
print("One-Hot Encoded Columns:", one_hot_encoded_cols)
print("Numerical Columns:", numerical_cols)

Dropped Columns: ['Timestamp']
Label Encoded Columns: ['gender', 'marital_status', 'sought_treatment']
Ordinal Mapped Columns: ['study_year', 'cgpa']
One-Hot Encoded Columns: ['course']
Numerical Columns: ['age']

## Define columntransformer

### Subtask:
Create a `ColumnTransformer` to apply appropriate preprocessing steps to different columns of the input data.

**Reasoning**:
Create a ColumnTransformer to handle the different preprocessing steps for the relevant columns, including one-hot encoding, label encoding, ordinal mapping for study year and CGPA, and scaling for age, while passing through the binary mental health issue columns.

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler
from sklearn.pipeline import Pipeline
import pandas as pd
import numpy as np

# Define the mapping for CGPA
cgpa_map = {
    '0 - 1.99': 1,
    '2.00 - 2.49': 1,
    '2.50 - 2.99': 2,
    '3.00 - 3.49': 2,
    '3.50 - 4.00': 3
}

# Custom transformer for CGPA mapping
def map_cgpa(X):
    return X.map(cgpa_map)

# Define transformers for different column types
preprocessor = ColumnTransformer(
    transformers=[
        ('onehot', OneHotEncoder(handle_unknown='ignore'), ['course']),
        ('label', LabelEncoder(), ['gender', 'marital_status', 'sought_treatment']),
        ('study_year', 'passthrough', ['study_year']), # study_year is already numerical from previous steps
        ('cgpa', FunctionTransformer(func=map_cgpa), ['cgpa']), # Use FunctionTransformer for the mapping
        ('scaler', StandardScaler(), ['age']),
        ('passthrough', 'passthrough', ['depression', 'anxiety', 'panic_attack']) # Pass through the already numerical columns
    ],
    remainder='passthrough' # Keep other columns (like Timestamp) - although Timestamp will be dropped later
)

# Note: For LabelEncoder within ColumnTransformer, it expects numerical output.
# The original notebook applied LabelEncoder directly which worked on binary 'Yes'/'No'.
# In a ColumnTransformer, it's more standard to use OneHotEncoder for nominals.
# However, to strictly follow the notebook's preprocessing on these specific binary columns,
# we'll keep LabelEncoder but acknowledge it might need adjustment if new categorical values appear.
# For the purpose of matching the notebook's preprocessing flow for these specific columns,
# we assume LabelEncoder works as it did previously on the transformed 0/1 values.
# A more robust approach for these binary features in a ColumnTransformer would be OneHotEncoder.

# Also, ensure that the 'study_year', 'depression', 'anxiety', 'panic_attack' columns are
# treated as numerical before passing them to the ColumnTransformer, matching their state in x_train.
# This will be handled in the subsequent steps when building the pipeline and fitting.

NameError: name 'FunctionTransformer' is not defined

**Reasoning**:
The previous command failed because FunctionTransformer was not imported. Import FunctionTransformer and regenerate the ColumnTransformer.

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler, FunctionTransformer
from sklearn.pipeline import Pipeline
import pandas as pd
import numpy as np

# Define the mapping for CGPA
cgpa_map = {
    '0 - 1.99': 1,
    '2.00 - 2.49': 1,
    '2.50 - 2.99': 2,
    '3.00 - 3.49': 2,
    '3.50 - 4.00': 3
}

# Custom transformer for CGPA mapping
def map_cgpa(X):
    return X.map(cgpa_map)

# Define transformers for different column types
preprocessor = ColumnTransformer(
    transformers=[
        ('onehot', OneHotEncoder(handle_unknown='ignore'), ['course']),
        ('label', LabelEncoder(), ['gender', 'marital_status', 'sought_treatment']),
        ('study_year', 'passthrough', ['study_year']), # study_year is already numerical from previous steps
        ('cgpa', FunctionTransformer(func=map_cgpa), ['cgpa']), # Use FunctionTransformer for the mapping
        ('scaler', StandardScaler(), ['age']),
        ('passthrough', 'passthrough', ['depression', 'anxiety', 'panic_attack']) # Pass through the already numerical columns
    ],
    remainder='passthrough' # Keep other columns (like Timestamp) - although Timestamp will be dropped later
)

# Note: For LabelEncoder within ColumnTransformer, it expects numerical output.
# The original notebook applied LabelEncoder directly which worked on binary 'Yes'/'No'.
# In a ColumnTransformer, it's more standard to use OneHotEncoder for nominals.
# However, to strictly follow the notebook's preprocessing on these specific binary columns,
# we'll keep LabelEncoder but acknowledge it might need adjustment if new categorical values appear.
# For the purpose of matching the notebook's preprocessing flow for these specific columns,
# we assume LabelEncoder works as it did previously on the transformed 0/1 values.
# A more robust approach for these binary features in a ColumnTransformer would be OneHotEncoder.

# Also, ensure that the 'study_year', 'depression', 'anxiety', 'panic_attack' columns are
# treated as numerical before passing them to the ColumnTransformer, matching their state in x_train.
# This will be handled in the subsequent steps when building the pipeline and fitting.

## Create pipeline

### Subtask:
Build a Pipeline that chains the `ColumnTransformer` and the `RandomForestClassifier` model.

**Reasoning**:
Build a Pipeline that chains the preprocessor and the forest model.

In [ ]:
pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                           ('classifier', forest)])

## Train the pipeline

### Subtask:
Fit the entire Pipeline on the training data (`x_train`, `y_train`).

**Reasoning**:
Fit the created pipeline to the training data to train the model with the defined preprocessing steps.

In [ ]:
pipeline.fit(x_train, y_train)

ValueError: A given column is not a column of the dataframe

**Reasoning**:
The error indicates that the ColumnTransformer is trying to access a column that does not exist in the input DataFrame. This is likely because the original `x_train` included one-hot encoded course columns and the original categorical 'course' column was dropped. The ColumnTransformer expects the original categorical column 'course' as input. We need to recreate `x_train` to include the original 'course' column.

In [ ]:
# Recreate x to include the original 'course' column before one-hot encoding
x = df.drop(columns = ['Timestamp', 'mental_issue'])
y = df['mental_issue']

# Split the data again with the corrected x
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, stratify = y, random_state = 42)

# Now fit the pipeline with the corrected x_train
pipeline.fit(x_train, y_train)

TypeError: LabelEncoder.fit_transform() takes 2 positional arguments but 3 were given

**Reasoning**:
The error "LabelEncoder.fit_transform() takes 2 positional arguments but 3 were given" within the ColumnTransformer indicates that the `LabelEncoder` is receiving `y` data when it should only receive `X`. This happens because the `ColumnTransformer`'s default behavior when `y` is provided to its `fit` method is to pass `y` to all transformers, which `LabelEncoder` does not expect. LabelEncoder should only operate on a single column of `X`. To fix this, we can modify the ColumnTransformer to use a different transformer for the binary columns that doesn't expect `y`, such as `OrdinalEncoder` with a specified mapping, or simply pass through the already transformed columns if they are available in the input `x_train`. Given that `depression`, `anxiety`, and `panic_attack` were already converted to numerical (0/1) in previous steps *before* creating `x_train` for the pipeline (as shown in the original notebook flow), they should be included in the `passthrough` list, and the `label` transformer should only handle 'gender' and 'marital_status', and 'sought_treatment' if they are still categorical. Let's re-examine the state of `x_train` after the split and before fitting the pipeline. The previous `df` which was used to create `x` already had 'depression', 'anxiety', and 'panic_attack' as numerical (0 or 1). So these should indeed be in the `passthrough`. The columns 'gender', 'marital_status', and 'sought_treatment' were label encoded *after* the `df` was created which was then used to create `x`. Thus, `x` created in the previous step still has 'gender', 'marital_status', and 'sought_treatment' as categorical. The ColumnTransformer needs to handle these. Using `OrdinalEncoder` is more appropriate in `ColumnTransformer` than `LabelEncoder` for this purpose, as it's designed to work within pipelines and handle multiple columns correctly, and we can provide the categories to ensure consistency.

Let's update the `preprocessor` to use `OrdinalEncoder` for the binary categorical columns ('gender', 'marital_status', 'sought_treatment') with explicit categories to ensure correct mapping, and keep 'depression', 'anxiety', and 'panic_attack' in the 'passthrough'.

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler, FunctionTransformer
from sklearn.pipeline import Pipeline
import pandas as pd
import numpy as np

# Define the mapping for CGPA
cgpa_map = {
    '0 - 1.99': 1,
    '2.00 - 2.49': 1,
    '2.50 - 2.99': 2,
    '3.00 - 3.49': 2,
    '3.50 - 4.00': 3
}

# Custom transformer for CGPA mapping
def map_cgpa(X):
    # Ensure X is a DataFrame and the column exists
    if isinstance(X, np.ndarray):
        # If input is a numpy array (which it will be inside ColumnTransformer),
        # the column selection and mapping need to be handled differently.
        # However, FunctionTransformer is designed to handle DataFrame inputs from ColumnTransformer
        # when column names are specified. Let's assume it works as intended.
        # A safer way might be to apply the mapping *before* the ColumnTransformer
        # or use a custom transformer class.
        # Given the context of fixing the current error, let's assume FunctionTransformer works
        # as expected with pandas Series/DataFrames passed by name from ColumnTransformer.
        # If X is an array at this point, mapping directly might be problematic without column names.
        # Let's stick to the DataFrame assumption as ColumnTransformer usually preserves this with column names.
         pass # ColumnTransformer should pass a Series or DataFrame slice

    return X.map(cgpa_map)

# Define transformers for different column types
preprocessor = ColumnTransformer(
    transformers=[
        ('onehot', OneHotEncoder(handle_unknown='ignore'), ['course']),
        ('ordinal', OrdinalEncoder(categories=[['Female', 'Male'], ['No', 'Yes'], ['No', 'Yes']]), ['gender', 'marital_status', 'sought_treatment']),
        ('study_year', 'passthrough', ['study_year']), # study_year is already numerical
        ('cgpa', FunctionTransformer(func=map_cgpa), ['cgpa']), # Use FunctionTransformer for the mapping
        ('scaler', StandardScaler(), ['age']),
        ('passthrough_binary', 'passthrough', ['depression', 'anxiety', 'panic_attack']) # Pass through the already numerical columns
    ],
    remainder='drop' # Drop other columns (like Timestamp)
)


# Recreate x to include the original 'course', 'gender', 'marital_status', 'sought_treatment' columns
x = df.drop(columns = ['Timestamp', 'mental_issue'])
y = df['mental_issue']

# Split the data again with the corrected x
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, stratify = y, random_state = 42)

# Create the pipeline again with the updated preprocessor
pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                           ('classifier', forest)])

# Now fit the pipeline with the corrected x_train
pipeline.fit(x_train, y_train)

TypeError: the first argument must be callable

**Reasoning**:
The error "TypeError: the first argument must be callable" within the `map_cgpa` function indicates that `X` is not a pandas Series when `.map()` is called. This is happening because `FunctionTransformer` within `ColumnTransformer` passes a NumPy array slice to the function, not a pandas Series with the column name. To correctly apply the mapping, we need to access the column data as a NumPy array and apply the mapping based on the numerical values or use a custom transformer that can handle the input correctly. A more robust way to handle the CGPA mapping within the pipeline is to use `OrdinalEncoder` similar to the binary categorical features, providing the categories and the desired numerical mapping.

Let's update the `preprocessor` to use `OrdinalEncoder` for 'cgpa' with explicit categories and corresponding numerical values.

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler
from sklearn.pipeline import Pipeline
import pandas as pd
import numpy as np

# Define the categories and their corresponding numerical values for CGPA
cgpa_categories = ['0 - 1.99', '2.00 - 2.49', '2.50 - 2.99', '3.00 - 3.49', '3.50 - 4.00']
cgpa_values = [1, 1, 2, 2, 3]

# Define transformers for different column types
preprocessor = ColumnTransformer(
    transformers=[
        ('onehot', OneHotEncoder(handle_unknown='ignore'), ['course']),
        ('ordinal_binary', OrdinalEncoder(categories=[['Female', 'Male'], ['No', 'Yes'], ['No', 'Yes']]), ['gender', 'marital_status', 'sought_treatment']),
        ('study_year', 'passthrough', ['study_year']), # study_year is already numerical
        ('ordinal_cgpa', OrdinalEncoder(categories=[cgpa_categories], dtype=int), ['cgpa']), # Use OrdinalEncoder for CGPA mapping
        ('scaler', StandardScaler(), ['age']),
        ('passthrough_binary', 'passthrough', ['depression', 'anxiety', 'panic_attack']) # Pass through the already numerical columns
    ],
    remainder='drop' # Drop other columns (like Timestamp)
)


# Recreate x to include the original 'course', 'gender', 'marital_status', 'sought_treatment', 'cgpa' columns
# and the already numerical 'study_year', 'depression', 'anxiety', 'panic_attack'
x = df.drop(columns = ['Timestamp', 'mental_issue'])
y = df['mental_issue']

# Split the data again with the corrected x
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, stratify = y, random_state = 42)

# Recreate the pipeline with the updated preprocessor
# Make sure the 'forest' object is still available from previous execution
pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                           ('classifier', forest)])

# Now fit the pipeline with the corrected x_train
pipeline.fit(x_train, y_train)

ValueError: Found unknown categories ['3.50 - 4.00 '] in column 0 during fit

**Reasoning**:
The error message "ValueError: Found unknown categories ['3.50 - 4.00 '] in column 0 during fit" indicates that there is a discrepancy between the categories provided to the `OrdinalEncoder` for the 'cgpa' column and the actual unique values present in the 'cgpa' column of the training data (`x_train`). The extra space at the end of '3.50 - 4.00 ' in the error message suggests a trailing space in the data that is not present in the `cgpa_categories` list. We need to clean the 'cgpa' column in `x_train` (and ideally the original `df` to ensure consistency) to remove any leading/trailing spaces before fitting the pipeline.

In [ ]:
# Clean the 'cgpa' column in the original dataframe to remove trailing spaces
df['cgpa'] = df['cgpa'].str.strip()

# Redefine cgpa_categories to match the cleaned data if necessary (though the current list looks correct)
cgpa_categories = ['0 - 1.99', '2.00 - 2.49', '2.50 - 2.99', '3.00 - 3.49', '3.50 - 4.00']
cgpa_values = [1, 1, 2, 2, 3] # These values are not directly used by OrdinalEncoder but kept for reference

# Define transformers for different column types - keep the OrdinalEncoder for CGPA
preprocessor = ColumnTransformer(
    transformers=[
        ('onehot', OneHotEncoder(handle_unknown='ignore'), ['course']),
        ('ordinal_binary', OrdinalEncoder(categories=[['Female', 'Male'], ['No', 'Yes'], ['No', 'Yes']]), ['gender', 'marital_status', 'sought_treatment']),
        ('study_year', 'passthrough', ['study_year']), # study_year is already numerical
        ('ordinal_cgpa', OrdinalEncoder(categories=[cgpa_categories], dtype=int), ['cgpa']), # Use OrdinalEncoder for CGPA mapping
        ('scaler', StandardScaler(), ['age']),
        ('passthrough_binary', 'passthrough', ['depression', 'anxiety', 'panic_attack']) # Pass through the already numerical columns
    ],
    remainder='drop' # Drop other columns (like Timestamp)
)


# Recreate x to include the original columns from the cleaned df
x = df.drop(columns = ['Timestamp', 'mental_issue'])
y = df['mental_issue']

# Split the data again with the corrected x
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, stratify = y, random_state = 42)

# Recreate the pipeline with the updated preprocessor
# Make sure the 'forest' object is still available from previous execution
pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                           ('classifier', forest)])

# Now fit the pipeline with the corrected x_train
pipeline.fit(x_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['course']),
                                                 ('ordinal_binary',
                                                  OrdinalEncoder(categories=[['Female',
                                                                              'Male'],
                                                                             ['No',
                                                                              'Yes'],
                                                                             ['No',
                                                                              'Yes']]),
                                                  ['gender', 'marital_status',
                                                   'sought_treatment']),
                                                 ('study_year', 'passthrough',
                                                  ['study_year']),
                                                 ('ordinal_cgpa',
                                                  OrdinalEncoder(categories=[['0 '
                                                                              '- '
                                                                              '1.99',
                                                                              '2.00 '
                                                                              '- '
                                                                              '2.49',
                                                                              '2.50 '
                                                                              '- '
                                                                              '2.99',
                                                                              '3.00 '
                                                                              '- '
                                                                              '3.49',
                                                                              '3.50 '
                                                                              '- '
                                                                              '4.00']],
                                                                 dtype=<class 'int'>),
                                                  ['cgpa']),
                                                 ('scaler', StandardScaler(),
                                                  ['age']),
                                                 ('passthrough_binary',
                                                  'passthrough',
                                                  ['depression', 'anxiety',
                                                   'panic_attack'])])),
                ('classifier',
                 RandomForestClassifier(class_weight='balanced',
                                        random_state=42))])

## Evaluate the pipeline

### Subtask:
Evaluate the performance of the trained Pipeline on the test data to ensure it's working correctly.

**Reasoning**:
Evaluate the performance of the trained pipeline by making predictions on the test set and printing the accuracy and classification report.

In [ ]:
pipeline_pred = pipeline.predict(x_test)
pipeline_accuracy = accuracy_score(y_test, pipeline_pred)
print(f"Pipeline Accuracy: {pipeline_accuracy}")
print(classification_report(y_test, pipeline_pred))

Pipeline Accuracy: 0.967741935483871
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        11
           2       0.94      1.00      0.97        17
           3       1.00      0.67      0.80         3

    accuracy                           0.97        31
   macro avg       0.98      0.89      0.92        31
weighted avg       0.97      0.97      0.96        31

## Save the pipeline

### Subtask:
Save the entire trained Pipeline (which includes the preprocessor and the model) to a `.pkl` file.

**Reasoning**:
Save the trained pipeline object to a file using joblib.

In [ ]:
import joblib
joblib.dump(pipeline, 'random_forest_pipeline.pkl')

['random_forest_pipeline.pkl']

## Modify streamlit app (load pipeline)

### Subtask:
Update the `app.py` file to load the saved Pipeline instead of just the model.

**Reasoning**:
Update the app.py script to load the pipeline.

In [ ]:
%%writefile app.py
import streamlit as st
import pandas as pd
import joblib
# We will load the pipeline which includes preprocessing, so LabelEncoder is not needed directly here for this purpose.
# from sklearn.preprocessing import LabelEncoder

# Load the trained Pipeline model
pipeline = joblib.load('random_forest_pipeline.pkl')

st.title('Student Mental Health Prediction')

st.write("""
This app predicts the mental health issue level of a student based on various factors.
Mental Health Issue Levels:
1: No issues
2: Moderate issues (Anxiety OR Panic Attack OR Depression)
3: Severe issues (Two or more issues)
""")

# Define the input fields
st.header('Enter Student Details:')

gender = st.selectbox('Choose your gender', ['Female', 'Male'])
age = st.number_input('Age', min_value=0, max_value=100, value=20)
course = st.selectbox('What is your course?', ['Engineering', 'Islamic education', 'BIT', 'Laws', 'Mathemathics', 'BCS', 'Human Resources', 'Irkhs', 'Psychology', 'KENMS', 'Accounting ', 'Medical Sciences', 'Pendidikan Islam ', 'Pendidikan Islam', 'Radiography', 'Dakwah', 'Diploma Nursing', 'Usuluddin ', 'FCIM', 'TAASL', 'Engine', 'Laws ', 'Kop', 'IRKHS', 'Dentistry', 'IT', 'CTS', 'engin', 'Econs', 'removing', 'psychology', 'koe', 'Kirkhs', 'Usuluddin', 'FSTE', 'Biomedical science', 'koe', 'BENL', 'Banking Studies', 'Diploma Science', 'MHSC', 'Malaysian studies', 'Nursing ', 'Pendidikan Islam', 'Human Sciences', 'business', 'Addin', 'Marine science', 'Pharmacy', 'Stock market ', 'Biotechnology', 'Communication ', 'Warning', 'Business Administration', 'Fiqh fatwa ', 'DVM ', 'Management ', 'syariah law ', 'Radiology', 'Diploma', 'Qaaf', 'Science', 'KOE', 'Islamic Education', 'Human science ', 'Biomedical Science', 'engin', 'Islamic finance', '建築工程', 'KMK', 'business', 'Diagnostic imaging ', 'Business', 'Law', 'Islamic finance ', 'Business', 'Diploma in accountancy', 'Renewable energy', 'Psychology', 'ENGINEERING', 'Banking islam', 'Software Engineering', 'Usul Fiqh ', 'Islamic Studies', 'engin ', 'ENM', 'Diploma in English', 'amway', 'Biotechnology ', 'Communication', 'Pendidikan', 'koe ', 'Fiqh', 'Islamic ed', 'Islamic Studies ', 'Aqidah', 'Manufacture', 'BIT ', 'Kirkhs ', 'Benl', 'IT ', 'machinical engineering', 'Laws', 'psychology', 'Pendidikan Islam', 'Human Science', 'Bcshons ', 'Marine science', 'Human resource', 'Accounting', 'Psychology', 'Radiography', 'TAASL', 'Usuluddin', 'engin', 'koe', 'psychology']) # Add all unique courses from your data
study_year = st.selectbox('Your current year of Study', [1, 2, 3, 4]) # Assuming years are 1, 2, 3, 4
cgpa = st.selectbox('What is your CGPA?', ['0 - 1.99', '2.00 - 2.49', '2.50 - 2.99', '3.00 - 3.49', '3.50 - 4.00'])
marital_status = st.selectbox('Marital status', ['No', 'Yes'])
sought_treatment = st.selectbox('Did you seek any specialist for a treatment?', ['No', 'Yes'])


# Preprocess user input
def preprocess_input(gender, age, course, study_year, cgpa, marital_status, sought_treatment):
    data = {'gender': gender,
            'age': age,
            'course': course,
            'study_year': study_year,
            'cgpa': cgpa,
            'marital_status': marital_status,
            'sought_treatment': sought_treatment,
            # Add these columns with default value 0 as they were present in the training data's initial state before the pipeline
            'depression': 0,
            'anxiety': 0,
            'panic_attack': 0
           }
    df_input = pd.DataFrame([data])

    # The pipeline handles all the preprocessing steps now, so we just return the DataFrame
    return df_input


# Create a button to make predictions
if st.button('Predict Mental Health Issue Level'):
    # Preprocess the input
    processed_input = preprocess_input(gender, age, course, study_year, cgpa, marital_status, sought_treatment)

    # Make prediction using the pipeline
    # The pipeline will handle all preprocessing and then make the prediction
    prediction = pipeline.predict(processed_input)

    # Display the prediction
    st.header('Prediction:')
    if prediction[0] == 1:
        st.success('Predicted Mental Health Issue Level: 1 (No issues)')
    elif prediction[0] == 2:
        st.warning('Predicted Mental Health Issue Level: 2 (Moderate issues)')
    else:
        st.error('Predicted Mental Health Issue Level: 3 (Severe issues)')

Overwriting app.py

## Modify streamlit app (preprocessing with pipeline)

### Subtask:
Update the `preprocess_input` function in `app.py` to pass the raw user input DataFrame directly to the loaded Pipeline's `predict` method. The Pipeline will handle the preprocessing internally.

**Reasoning**:
Update the app.py script to remove the manual preprocessing steps within the preprocess_input function and make it return the raw DataFrame. Also, update the prediction call to use the pipeline directly on the output of preprocess_input.

In [ ]:
%%writefile app.py
import streamlit as st
import pandas as pd
import joblib
# We will load the pipeline which includes preprocessing, so LabelEncoder is not needed directly here for this purpose.
# from sklearn.preprocessing import LabelEncoder

# Load the trained Pipeline model
pipeline = joblib.load('random_forest_pipeline.pkl')

st.title('Student Mental Health Prediction')

st.write("""
This app predicts the mental health issue level of a student based on various factors.
Mental Health Issue Levels:
1: No issues
2: Moderate issues (Anxiety OR Panic Attack OR Depression)
3: Severe issues (Two or more issues)
""")

# Define the input fields
st.header('Enter Student Details:')

gender = st.selectbox('Choose your gender', ['Female', 'Male'])
age = st.number_input('Age', min_value=0, max_value=100, value=20)
course = st.selectbox('What is your course?', ['Engineering', 'Islamic education', 'BIT', 'Laws', 'Mathemathics', 'BCS', 'Human Resources', 'Irkhs', 'Psychology', 'KENMS', 'Accounting ', 'Medical Sciences', 'Pendidikan Islam ', 'Pendidikan Islam', 'Radiography', 'Dakwah', 'Diploma Nursing', 'Usuluddin ', 'FCIM', 'TAASL', 'Engine', 'Laws ', 'Kop', 'IRKHS', 'Dentistry', 'IT', 'CTS', 'engin', 'Econs', 'removing', 'psychology', 'koe', 'Kirkhs', 'Usuluddin', 'FSTE', 'Biomedical science', 'koe', 'BENL', 'Banking Studies', 'Diploma Science', 'MHSC', 'Malaysian studies', 'Nursing ', 'Pendidikan Islam', 'Human Sciences', 'business', 'Addin', 'Marine science', 'Pharmacy', 'Stock market ', 'Biotechnology', 'Communication ', 'Warning', 'Business Administration', 'Fiqh fatwa ', 'DVM ', 'Management ', 'syariah law ', 'Radiology', 'Diploma', 'Qaaf', 'Science', 'KOE', 'Islamic Education', 'Human science ', 'Biomedical Science', 'engin', 'Islamic finance', '建築工程', 'KMK', 'business', 'Diagnostic imaging ', 'Business', 'Law', 'Islamic finance ', 'Business', 'Diploma in accountancy', 'Renewable energy', 'Psychology', 'ENGINEERING', 'Banking islam', 'Software Engineering', 'Usul Fiqh ', 'Islamic Studies', 'engin ', 'ENM', 'Diploma in English', 'amway', 'Biotechnology ', 'Communication', 'Pendidikan', 'koe ', 'Fiqh', 'Islamic ed', 'Islamic Studies ', 'Aqidah', 'Manufacture', 'BIT ', 'Kirkhs ', 'Benl', 'IT ', 'machinical engineering', 'Laws', 'psychology', 'Pendidikan Islam', 'Human Science', 'Bcshons ', 'Marine science', 'Human resource', 'Accounting', 'Psychology', 'Radiography', 'TAASL', 'Usuluddin', 'engin', 'koe', 'psychology']) # Add all unique courses from your data
study_year = st.selectbox('Your current year of Study', [1, 2, 3, 4]) # Assuming years are 1, 2, 3, 4
cgpa = st.selectbox('What is your CGPA?', ['0 - 1.99', '2.00 - 2.49', '2.50 - 2.99', '3.00 - 3.49', '3.50 - 4.00'])
marital_status = st.selectbox('Marital status', ['No', 'Yes'])
sought_treatment = st.selectbox('Did you seek any specialist for a treatment?', ['No', 'Yes'])


# Preprocess user input
def preprocess_input(gender, age, course, study_year, cgpa, marital_status, sought_treatment):
    data = {'gender': gender,
            'age': age,
            'course': course,
            'study_year': study_year,
            'cgpa': cgpa,
            'marital_status': marital_status,
            'sought_treatment': sought_treatment,
            # Add these columns with default value 0 as they were present in the training data's initial state before the pipeline
            'depression': 0,
            'anxiety': 0,
            'panic_attack': 0
           }
    df_input = pd.DataFrame([data])

    # The pipeline handles all the preprocessing steps now, so we just return the DataFrame
    return df_input


# Create a button to make predictions
if st.button('Predict Mental Health Issue Level'):
    # Get the raw input as a DataFrame
    raw_input_df = preprocess_input(gender, age, course, study_year, cgpa, marital_status, sought_treatment)

    # Make prediction using the pipeline
    # The pipeline will handle all preprocessing and then make the prediction
    prediction = pipeline.predict(raw_input_df)

    # Display the prediction
    st.header('Prediction:')
    if prediction[0] == 1:
        st.success('Predicted Mental Health Issue Level: 1 (No issues)')
    elif prediction[0] == 2:
        st.warning('Predicted Mental Health Issue Level: 2 (Moderate issues)')
    else:
        st.error('Predicted Mental Health Issue Level: 3 (Severe issues)')

Overwriting app.py

## Test streamlit app

### Subtask:
Run the Streamlit app locally to ensure it works correctly with the Pipeline.

## Summary:

### Data Analysis Key Findings

*   The initial preprocessing steps involved dropping the 'Timestamp' column, label encoding 'gender', 'marital\_status', and 'sought\_treatment', mapping 'study\_year' and 'cgpa' to numerical values, one-hot encoding 'course', and keeping 'age' as is. Additionally, 'depression', 'anxiety', and 'panic\_attack' were treated as numerical features derived from previous steps.
*   A `ColumnTransformer` was successfully defined to apply these preprocessing steps within a pipeline, using `OneHotEncoder` for 'course', `OrdinalEncoder` for binary categorical features and 'cgpa', `StandardScaler` for 'age', and passing through 'study\_year', 'depression', 'anxiety', and 'panic\_attack'.
*   Trailing spaces in the 'cgpa' column of the original data caused a `ValueError` during pipeline fitting with `OrdinalEncoder`. Cleaning the 'cgpa' column by stripping spaces was necessary for successful training.
*   The scikit-learn `Pipeline` chaining the `ColumnTransformer` and the `RandomForestClassifier` achieved an accuracy of 0.9677 on the test data.
*   The trained pipeline was successfully saved to `random_forest_pipeline.pkl` using `joblib`.
*   The `app.py` script was updated to load the saved pipeline and use it directly for prediction, passing the raw user input DataFrame to `pipeline.predict()`, which handles all internal preprocessing.

### Insights or Next Steps

*   Using a scikit-learn `Pipeline` effectively encapsulates both preprocessing and modeling, ensuring consistency between training and inference and simplifying deployment.
*   Ensure data consistency and cleanliness (e.g., handling trailing spaces, consistent casing) in both training and production data to prevent errors when using transformers like `OrdinalEncoder`.

## Identify preprocessing steps

### Subtask:
Identify preprocessing steps for each column based on the previous steps in the notebook.

**Reasoning**:
Analyze the previous code cells to identify the preprocessing steps applied to each column and categorize them accordingly.

In [ ]:
# Identify dropped columns
dropped_columns = ['Timestamp']

# Identify binary categorical columns label encoded
label_encoded_cols = ['gender', 'marital_status', 'sought_treatment']

# Identify ordinal categorical columns mapped to numerical
ordinal_mapped_cols = ['study_year', 'cgpa']

# Identify nominal categorical columns one-hot encoded
one_hot_encoded_cols = ['course']

# Identify numerical columns kept as is
numerical_cols = ['age']

# Columns created during preprocessing that are used as features (from the sum of binary depression/anxiety/panic)
# These columns are already present in x_train, so we don't need to process them from the original input in the app
# They will be added with default 0 in the app's preprocessing function.
# features_from_binary_sum = ['depression', 'anxiety', 'panic_attack']

print("Dropped Columns:", dropped_columns)
print("Label Encoded Columns:", label_encoded_cols)
print("Ordinal Mapped Columns:", ordinal_mapped_cols)
print("One-Hot Encoded Columns:", one_hot_encoded_cols)
print("Numerical Columns:", numerical_cols)

Dropped Columns: ['Timestamp']
Label Encoded Columns: ['gender', 'marital_status', 'sought_treatment']
Ordinal Mapped Columns: ['study_year', 'cgpa']
One-Hot Encoded Columns: ['course']
Numerical Columns: ['age']

## Define columntransformer

### Subtask:
Create a `ColumnTransformer` to apply appropriate preprocessing steps to different columns of the input data.

**Reasoning**:
Create a ColumnTransformer to handle the different preprocessing steps for the relevant columns, including one-hot encoding, label encoding, ordinal mapping for study year and CGPA, and scaling for age, while passing through the binary mental health issue columns.

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler, FunctionTransformer
from sklearn.pipeline import Pipeline
import pandas as pd
import numpy as np

# Define the mapping for CGPA (for reference, OrdinalEncoder will handle the mapping)
cgpa_map = {
    '0 - 1.99': 1,
    '2.00 - 2.49': 1,
    '2.50 - 2.99': 2,
    '3.00 - 3.49': 2,
    '3.50 - 4.00': 3
}

# Define categories for OrdinalEncoder
gender_categories = ['Female', 'Male']
marital_status_categories = ['No', 'Yes']
sought_treatment_categories = ['No', 'Yes']
cgpa_categories = ['0 - 1.99', '2.00 - 2.49', '2.50 - 2.99', '3.00 - 3.49', '3.50 - 4.00']


# Define transformers for different column types
preprocessor = ColumnTransformer(
    transformers=[
        ('onehot', OneHotEncoder(handle_unknown='ignore'), ['course']),
        ('ordinal_binary', OrdinalEncoder(categories=[gender_categories, marital_status_categories, sought_treatment_categories]), ['gender', 'marital_status', 'sought_treatment']),
        ('study_year', 'passthrough', ['study_year']), # study_year is already numerical
        ('ordinal_cgpa', OrdinalEncoder(categories=[cgpa_categories], dtype=int), ['cgpa']), # Use OrdinalEncoder for CGPA mapping
        ('scaler', StandardScaler(), ['age']),
        ('passthrough_binary', 'passthrough', ['depression', 'anxiety', 'panic_attack']) # Pass through the already numerical columns
    ],
    remainder='drop' # Drop other columns (like Timestamp)
)

# Note: Ensure that the 'study_year', 'depression', 'anxiety', 'panic_attack' columns are
# treated as numerical before passing them to the ColumnTransformer, matching their state in x_train.
# This will be handled in the subsequent steps when building the pipeline and fitting.

## Create pipeline

### Subtask:
Build a Pipeline that chains the `ColumnTransformer` and the `RandomForestClassifier` model.

**Reasoning**:
Build a Pipeline that chains the preprocessor and the forest model.

In [ ]:
pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                           ('classifier', forest)])

## Train the pipeline

### Subtask:
Fit the entire Pipeline on the training data (`x_train`, `y_train`).

**Reasoning**:
Fit the created pipeline to the training data to train the model with the defined preprocessing steps.

In [ ]:
pipeline.fit(x_train, y_train)

TypeError: LabelEncoder.fit_transform() takes 2 positional arguments but 3 were given

In [ ]:
# Recreate x to include the original 'course', 'gender', 'marital_status', 'sought_treatment' columns
# and the already numerical 'study_year', 'depression', 'anxiety', 'panic_attack'
x = df.drop(columns = ['Timestamp', 'mental_issue'])
y = df['mental_issue']

# Split the data again with the corrected x
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, stratify = y, random_state = 42)

# Create the pipeline again with the updated preprocessor
# Make sure the 'forest' object is still available from previous execution
pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                           ('classifier', forest)])

# Now fit the pipeline with the corrected x_train
pipeline.fit(x_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['course']),
                                                 ('ordinal_binary',
                                                  OrdinalEncoder(categories=[['Female',
                                                                              'Male'],
                                                                             ['No',
                                                                              'Yes'],
                                                                             ['No',
                                                                              'Yes']]),
                                                  ['gender', 'marital_status',
                                                   'sought_treatment']),
                                                 ('study_year', 'passthrough',
                                                  ['study_year']),
                                                 ('ordinal_cgpa',
                                                  OrdinalEncoder(categories=[['0 '
                                                                              '- '
                                                                              '1.99',
                                                                              '2.00 '
                                                                              '- '
                                                                              '2.49',
                                                                              '2.50 '
                                                                              '- '
                                                                              '2.99',
                                                                              '3.00 '
                                                                              '- '
                                                                              '3.49',
                                                                              '3.50 '
                                                                              '- '
                                                                              '4.00']],
                                                                 dtype=<class 'int'>),
                                                  ['cgpa']),
                                                 ('scaler', StandardScaler(),
                                                  ['age']),
                                                 ('passthrough_binary',
                                                  'passthrough',
                                                  ['depression', 'anxiety',
                                                   'panic_attack'])])),
                ('classifier',
                 RandomForestClassifier(class_weight='balanced',
                                        random_state=42))])

## Evaluate the pipeline

### Subtask:
Evaluate the performance of the trained Pipeline on the test data to ensure it's working correctly.

**Reasoning**:
Evaluate the performance of the trained pipeline by making predictions on the test set and printing the accuracy and classification report.

In [ ]:
pipeline_pred = pipeline.predict(x_test)
pipeline_accuracy = accuracy_score(y_test, pipeline_pred)
print(f"Pipeline Accuracy: {pipeline_accuracy}")
print(classification_report(y_test, pipeline_pred))

Pipeline Accuracy: 0.967741935483871
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        11
           2       0.94      1.00      0.97        17
           3       1.00      0.67      0.80         3

    accuracy                           0.97        31
   macro avg       0.98      0.89      0.92        31
weighted avg       0.97      0.97      0.96        31

## Save the pipeline

### Subtask:
Save the entire trained Pipeline (which includes the preprocessor and the model) to a `.pkl` file.

**Reasoning**:
Save the trained pipeline object to a file using joblib.

In [ ]:
import joblib
joblib.dump(pipeline, 'random_forest_pipeline.pkl')

['random_forest_pipeline.pkl']

## Modify streamlit app (load pipeline)

### Subtask:
Update the `app.py` file to load the saved Pipeline instead of just the model.

**Reasoning**:
Update the app.py script to load the pipeline.

In [ ]:
%%writefile app.py
import streamlit as st
import pandas as pd
import joblib
# We will load the pipeline which includes preprocessing, so LabelEncoder is not needed directly here for this purpose.
# from sklearn.preprocessing import LabelEncoder

# Load the trained Pipeline model
pipeline = joblib.load('random_forest_pipeline.pkl')

st.title('Student Mental Health Prediction')

st.write("""
This app predicts the mental health issue level of a student based on various factors.
Mental Health Issue Levels:
1: No issues
2: Moderate issues (Anxiety OR Panic Attack OR Depression)
3: Severe issues (Two or more issues)
""")

# Define the input fields
st.header('Enter Student Details:')

gender = st.selectbox('Choose your gender', ['Female', 'Male'])
age = st.number_input('Age', min_value=0, max_value=100, value=20)
course = st.selectbox('What is your course?', ['Engineering', 'Islamic education', 'BIT', 'Laws', 'Mathemathics', 'BCS', 'Human Resources', 'Irkhs', 'Psychology', 'KENMS', 'Accounting ', 'Medical Sciences', 'Pendidikan Islam ', 'Pendidikan Islam', 'Radiography', 'Dakwah', 'Diploma Nursing', 'Usuluddin ', 'FCIM', 'TAASL', 'Engine', 'Laws ', 'Kop', 'IRKHS', 'Dentistry', 'IT', 'CTS', 'engin', 'Econs', 'removing', 'psychology', 'koe', 'Kirkhs', 'Usuluddin', 'FSTE', 'Biomedical science', 'koe', 'BENL', 'Banking Studies', 'Diploma Science', 'MHSC', 'Malaysian studies', 'Nursing ', 'Pendidikan Islam', 'Human Sciences', 'business', 'Addin', 'Marine science', 'Pharmacy', 'Stock market ', 'Biotechnology', 'Communication ', 'Warning', 'Business Administration', 'Fiqh fatwa ', 'DVM ', 'Management ', 'syariah law ', 'Radiology', 'Diploma', 'Qaaf', 'Science', 'KOE', 'Islamic Education', 'Human science ', 'Biomedical Science', 'engin', 'Islamic finance', '建築工程', 'KMK', 'business', 'Diagnostic imaging ', 'Business', 'Law', 'Islamic finance ', 'Business', 'Diploma in accountancy', 'Renewable energy', 'Psychology', 'ENGINEERING', 'Banking islam', 'Software Engineering', 'Usul Fiqh ', 'Islamic Studies', 'engin ', 'ENM', 'Diploma in English', 'amway', 'Biotechnology ', 'Communication', 'Pendidikan', 'koe ', 'Fiqh', 'Islamic ed', 'Islamic Studies ', 'Aqidah', 'Manufacture', 'BIT ', 'Kirkhs ', 'Benl', 'IT ', 'machinical engineering', 'Laws', 'psychology', 'Pendidikan Islam', 'Human Science', 'Bcshons ', 'Marine science', 'Human resource', 'Accounting', 'Psychology', 'Radiography', 'TAASL', 'Usuluddin', 'engin', 'koe', 'psychology']) # Add all unique courses from your data
study_year = st.selectbox('Your current year of Study', [1, 2, 3, 4]) # Assuming years are 1, 2, 3, 4
cgpa = st.selectbox('What is your CGPA?', ['0 - 1.99', '2.00 - 2.49', '2.50 - 2.99', '3.00 - 3.49', '3.50 - 4.00'])
marital_status = st.selectbox('Marital status', ['No', 'Yes'])
sought_treatment = st.selectbox('Did you seek any specialist for a treatment?', ['No', 'Yes'])


# Preprocess user input
def preprocess_input(gender, age, course, study_year, cgpa, marital_status, sought_treatment):
    data = {'gender': gender,
            'age': age,
            'course': course,
            'study_year': study_year,
            'cgpa': cgpa,
            'marital_status': marital_status,
            'sought_treatment': sought_treatment,
            # Add these columns with default value 0 as they were present in the training data's initial state before the pipeline
            'depression': 0,
            'anxiety': 0,
            'panic_attack': 0
           }
    df_input = pd.DataFrame([data])

    # The pipeline handles all the preprocessing steps now, so we just return the DataFrame
    return df_input


# Create a button to make predictions
if st.button('Predict Mental Health Issue Level'):
    # Preprocess the input
    processed_input = preprocess_input(gender, age, course, study_year, cgpa, marital_status, sought_treatment)

    # Make prediction using the pipeline
    # The pipeline will handle all preprocessing and then make the prediction
    prediction = pipeline.predict(processed_input)

    # Display the prediction
    st.header('Prediction:')
    if prediction[0] == 1:
        st.success('Predicted Mental Health Issue Level: 1 (No issues)')
    elif prediction[0] == 2:
        st.warning('Predicted Mental Health Issue Level: 2 (Moderate issues)')
    else:
        st.error('Predicted Mental Health Issue Level: 3 (Severe issues)')

Overwriting app.py

## Modify streamlit app (preprocessing with pipeline)

### Subtask:
Update the `preprocess_input` function in `app.py` to pass the raw user input DataFrame directly to the loaded Pipeline's `predict` method. The Pipeline will handle the preprocessing internally.

**Reasoning**:
Update the app.py script to remove the manual preprocessing steps within the preprocess_input function and make it return the raw DataFrame. Also, update the prediction call to use the pipeline directly on the output of preprocess_input.

In [ ]:
%%writefile app.py
import streamlit as st
import pandas as pd
import joblib
# We will load the pipeline which includes preprocessing, so LabelEncoder is not needed directly here for this purpose.
# from sklearn.preprocessing import LabelEncoder

# Load the trained Pipeline model
pipeline = joblib.load('random_forest_pipeline.pkl')

st.title('Student Mental Health Prediction')

st.write("""
This app predicts the mental health issue level of a student based on various factors.
Mental Health Issue Levels:
1: No issues
2: Moderate issues (Anxiety OR Panic Attack OR Depression)
3: Severe issues (Two or more issues)
""")

# Define the input fields
st.header('Enter Student Details:')

gender = st.selectbox('Choose your gender', ['Female', 'Male'])
age = st.number_input('Age', min_value=0, max_value=100, value=20)
course = st.selectbox('What is your course?', ['Engineering', 'Islamic education', 'BIT', 'Laws', 'Mathemathics', 'BCS', 'Human Resources', 'Irkhs', 'Psychology', 'KENMS', 'Accounting ', 'Medical Sciences', 'Pendidikan Islam ', 'Pendidikan Islam', 'Radiography', 'Dakwah', 'Diploma Nursing', 'Usuluddin ', 'FCIM', 'TAASL', 'Engine', 'Laws ', 'Kop', 'IRKHS', 'Dentistry', 'IT', 'CTS', 'engin', 'Econs', 'removing', 'psychology', 'koe', 'Kirkhs', 'Usuluddin', 'FSTE', 'Biomedical science', 'koe', 'BENL', 'Banking Studies', 'Diploma Science', 'MHSC', 'Malaysian studies', 'Nursing ', 'Pendidikan Islam', 'Human Sciences', 'business', 'Addin', 'Marine science', 'Pharmacy', 'Stock market ', 'Biotechnology', 'Communication ', 'Warning', 'Business Administration', 'Fiqh fatwa ', 'DVM ', 'Management ', 'syariah law ', 'Radiology', 'Diploma', 'Qaaf', 'Science', 'KOE', 'Islamic Education', 'Human science ', 'Biomedical Science', 'engin', 'Islamic finance', '建築工程', 'KMK', 'business', 'Diagnostic imaging ', 'Business', 'Law', 'Islamic finance ', 'Business', 'Diploma in accountancy', 'Renewable energy', 'Psychology', 'ENGINEERING', 'Banking islam', 'Software Engineering', 'Usul Fiqh ', 'Islamic Studies', 'engin ', 'ENM', 'Diploma in English', 'amway', 'Biotechnology ', 'Communication', 'Pendidikan', 'koe ', 'Fiqh', 'Islamic ed', 'Islamic Studies ', 'Aqidah', 'Manufacture', 'BIT ', 'Kirkhs ', 'Benl', 'IT ', 'machinical engineering', 'Laws', 'psychology', 'Pendidikan Islam', 'Human Science', 'Bcshons ', 'Marine science', 'Human resource', 'Accounting', 'Psychology', 'Radiography', 'TAASL', 'Usuluddin', 'engin', 'koe', 'psychology']) # Add all unique courses from your data
study_year = st.selectbox('Your current year of Study', [1, 2, 3, 4]) # Assuming years are 1, 2, 3, 4
cgpa = st.selectbox('What is your CGPA?', ['0 - 1.99', '2.00 - 2.49', '2.50 - 2.99', '3.00 - 3.49', '3.50 - 4.00'])
marital_status = st.selectbox('Marital status', ['No', 'Yes'])
sought_treatment = st.selectbox('Did you seek any specialist for a treatment?', ['No', 'Yes'])

# Add input fields for the individual mental health conditions
depression_input = st.selectbox('Do you have Depression?', ['No', 'Yes'])
anxiety_input = st.selectbox('Do you have Anxiety?', ['No', 'Yes'])
panic_attack_input = st.selectbox('Do you have Panic attack?', ['No', 'Yes'])


# Preprocess user input
def preprocess_input(gender, age, course, study_year, cgpa, marital_status, sought_treatment, depression_input, anxiety_input, panic_attack_input):
    data = {'gender': gender,
            'age': age,
            'course': course,
            'study_year': study_year,
            'cgpa': cgpa,
            'marital_status': marital_status,
            'sought_treatment': sought_treatment,
            # Convert Yes/No inputs to 0/1 for these columns
            'depression': 1 if depression_input == 'Yes' else 0,
            'anxiety': 1 if anxiety_input == 'Yes' else 0,
            'panic_attack': 1 if panic_attack_input == 'Yes' else 0
           }
    df_input = pd.DataFrame([data])

    # The pipeline handles all the preprocessing steps now, so we just return the DataFrame
    return df_input


# Create a button to make predictions
if st.button('Predict Mental Health Issue Level'):
    # Get the raw input as a DataFrame
    raw_input_df = preprocess_input(gender, age, course, study_year, cgpa, marital_status, sought_treatment, depression_input, anxiety_input, panic_attack_input)

    # Make prediction using the pipeline
    # The pipeline will handle all preprocessing and then make the prediction
    prediction = pipeline.predict(raw_input_df)

    # Display the prediction
    st.header('Prediction:')
    if prediction[0] == 1:
        st.success('Predicted Mental Health Issue Level: 1 (No issues)')
    elif prediction[0] == 2:
        st.warning('Predicted Mental Health Issue Level: 2 (Moderate issues)')
    else:
        st.error('Predicted Mental Health Issue Level: 3 (Severe issues)')

Overwriting app.py

## Test streamlit app

### Subtask:
Run the Streamlit app locally to ensure it works correctly with the Pipeline.